import { reportDirectory, browserOptions, qaBaseURL } from './qa-support.mjs';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
const output = path.resolve(reportDirectory(import.meta.url)); await mkdir(output, { recursive: true });
const browser = await chromium.launch({...browserOptions,  headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 820 } });
const errors = [], checks = []; page.on('pageerror', error => errors.push(error.message));
const near = (actual, expected, epsilon = .7) => assert.ok(Math.abs(actual - expected) < epsilon, `${actual} != ${expected}`);
const view = () => page.locator('.canvas-world, .inner-canvas-world').first().evaluate(node => { const m = new DOMMatrix(getComputedStyle(node).transform); return { x: m.e, y: m.f, zoom: m.a }; });
const size = () => page.locator('.asset-canvas, .asset-inner-canvas').evaluate(node => ({ width: node.clientWidth, height: node.clientHeight }));
const map = () => page.locator('.canvas-minimap');
const setView = async value => { await page.evaluate(value => window.minimapQA.setView(value), value); await page.waitForTimeout(320); };
try {
  await page.goto(`${qaBaseURL}/scripts/verify-minimap.html`); await map().waitFor();
  await page.waitForFunction(() => document.querySelectorAll('.minimap-note').length === 1 && document.querySelectorAll('.minimap-text').length === 1);
  assert.equal(await map().count(), 1); assert.equal(await map().locator('image,img,text').count(), 0);
  const layout = await map().evaluate(node => { const a = node.getBoundingClientRect(), b = document.querySelector('.canvas-controls').getBoundingClientRect(); return { width: a.width, height: a.height, gap: b.top - a.bottom, right: b.right - a.right }; });
  near(layout.width, 220); near(layout.height, 150); near(layout.gap, 12); near(layout.right, 0);
  checks.push('外画布只有一个色块地图，220×150、工具栏间距12px及右对齐');
  for (const mode of ['outer', 'inner']) {
    await page.evaluate(mode => window.minimapQA.setMode(mode), mode); await map().waitFor();
    const objectId = mode === 'outer' ? 'asset:qa-asset' : 'item:sample';
    for (const uiScale of [.75, 1, 1.5]) for (const zoom of [.1, .51, 1, 5]) {
      await page.evaluate(scale => document.documentElement.style.setProperty('--ui-scale', scale), uiScale);
      await setView({ viewportX: -18000 * zoom, viewportY: -8000 * zoom, zoom });
      const rect = await map().locator(`[data-minimap-id="${objectId}"]`).boundingBox();
      await page.evaluate(() => document.addEventListener('pointerdown', event => { window.minimapDown = { x: event.clientX, y: event.clientY, target: event.target.outerHTML.slice(0, 100) }; }, { once: true, capture: true }));
      await page.mouse.click(rect.x + rect.width / 2, rect.y + rect.height / 2);
      const actual = await view(), surface = await size();
      const down = await page.evaluate(() => window.minimapDown);
      const clickedWorld = { x: -600 + (down.x - rect.x) / rect.width * 400, y: -300 + (down.y - rect.y) / rect.height * 300 };
      near(actual.x + clickedWorld.x * actual.zoom, surface.width / 2); near(actual.y + clickedWorld.y * actual.zoom, surface.height / 2); near(actual.zoom, zoom, .00001);
      const before = await view(), hit = await map().locator('.minimap-viewport-hit').boundingBox();
      assert.ok(hit.width / uiScale >= 23.9 && hit.height / uiScale >= 23.9);
      const markerBefore = await map().locator(`[data-minimap-id="${objectId}"]`).boundingBox();
      const scale = markerBefore.width / uiScale / 400;
      await page.mouse.move(hit.x + hit.width / 2, hit.y + hit.height / 2); await page.mouse.down();
      await page.mouse.move(hit.x + hit.width / 2 + 14 * uiScale, hit.y + hit.height / 2 + 6 * uiScale, { steps: 5 });
      const during = await view(), markerDuring = await map().locator(`[data-minimap-id="${objectId}"]`).boundingBox();
      near(during.x, before.x - 14 / scale * zoom, 2); near(during.y, before.y - 6 / scale * zoom, 2);
      near(markerDuring.x, markerBefore.x, .05); near(markerDuring.width, markerBefore.width, .05);
      await page.mouse.up();
      const wheelBefore = await view(), svg = await map().locator('svg[role=application]').boundingBox();
      await page.mouse.move(svg.x + 8, svg.y + 8); await page.mouse.wheel(0, -300); await page.waitForTimeout(50);
      assert.deepEqual(await view(), wheelBefore);
      await page.mouse.click(svg.x + 8, svg.y + 8, { button: 'right' });
      assert.equal(await page.locator('.canvas-context-menu,.inner-canvas-context-menu').count(), 0);
      await page.waitForTimeout(320); // Let the inner canvas's existing viewport save finish before changing fixture props.
    }
    checks.push(`${mode}: 3种界面缩放×4种画布缩放，负坐标定位、24px命中、拖动映射固定、滚轮/右键隔离`);
  }
  await page.evaluate(() => { document.documentElement.style.setProperty('--ui-scale', '1'); window.minimapQA.setMode('outer'); }); await map().waitFor();
  const assetsBefore = await page.evaluate(() => window.minimapQA.assets);
  const svg = await map().locator('svg[role=application]').boundingBox(); await page.mouse.dblclick(svg.x + 4, svg.y + 4);
  assert.deepEqual(await page.evaluate(() => window.minimapQA.assets), assetsBefore);
  assert.equal(await page.locator('.canvas-selection-box,.inner-canvas-selection').count(), 0);
  assert.equal(await page.locator('.minimap-text').count(), 1);
  await page.getByRole('button', { name: '画布背景', exact: true }).click(); assert.equal(await map().count(), 0);
  await page.getByRole('button', { name: '画布背景', exact: true }).click(); await map().waitFor();
  await page.getByRole('button', { name: '收起小地图', exact: true }).click(); assert.equal(await map().count(), 0);
  await page.reload(); await page.waitForSelector('.asset-canvas'); assert.equal(await map().count(), 0);
  await page.evaluate(() => window.minimapQA.setMode('inner')); await map().waitFor();
  await page.evaluate(() => window.minimapQA.setMode('outer')); await page.waitForSelector('.asset-canvas'); assert.equal(await map().count(), 0);
  await page.getByRole('button', { name: '小地图', exact: true }).click(); await map().waitFor();
  checks.push('双击不创建文字或移动资产，背景面板避让，内外开关独立记忆并重载恢复');
  await page.evaluate(() => window.minimapQA.setAssets(window.minimapQA.assets.filter(item => item.id !== 'far-asset')));
  await setView({ viewportX: 800, viewportY: 450, zoom: 1 });
  const noteBefore = await map().locator('.minimap-note').evaluate(node => +node.getAttribute('width'));
  await page.getByRole('button', { name: '收起备注', exact: true }).click();
  await page.waitForFunction(width => +document.querySelector('.minimap-note').getAttribute('width') < width / 2, noteBefore);
  await page.getByRole('button', { name: '展开备注：备注', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.asset-note-drawer')?.dataset.mode === 'docked-expanded');
  const drawer = page.locator('.asset-note-drawer-header'), drawerRect = await drawer.boundingBox();
  const noteGeometry = await map().locator('.minimap-note').evaluate(node => ['x','y','width','height','points'].map(key => node.getAttribute(key)));
  await page.mouse.move(drawerRect.x + 30, drawerRect.y + 8); await page.mouse.down(); await page.mouse.move(drawerRect.x + 65, drawerRect.y + 100, { steps: 8 });
  assert.notDeepEqual(await map().locator('.minimap-note').evaluate(node => ['x','y','width','height','points'].map(key => node.getAttribute(key))), noteGeometry); await page.mouse.up();
  checks.push('真实备注展开/收起后缩略矩形同步，拖动预览实时更新');
  await page.evaluate(() => window.minimapQA.setAssets(current => current.map(item => ({ ...item, rotation: 35 }))));
  await page.waitForFunction(() => document.querySelector('[data-minimap-id="asset:qa-asset"]')?.tagName.toLowerCase() === 'polygon');
  assert.equal(await map().locator('[data-minimap-id="asset:qa-asset"]').evaluate(node => node.points.numberOfItems), 4);
  await page.evaluate(() => window.minimapQA.setAssets(current => current.map(item => ({ ...item, rotation: 0 }))));
  await page.evaluate(() => window.minimapQA.setMode('inner')); await map().waitFor();
  await page.evaluate(() => window.minimapQA.setInnerObjects(current => current.map(item => ({ ...item, rotation: -25 }))));
  await page.waitForFunction(() => document.querySelector('[data-minimap-id="item:sample"]')?.tagName.toLowerCase() === 'polygon');
  await page.screenshot({ path: path.join(output, 'inner-rotated.png') });
  await page.evaluate(() => { window.minimapQA.setInnerObjects(current => current.map(item => ({ ...item, rotation: 0 }))); window.minimapQA.setMode('outer'); }); await map().waitFor();
  checks.push('兼容并行新增的旋转：内外对象角度与实际占用范围同步为色块');
  await page.evaluate(() => window.minimapQA.setSearch('远处')); await page.waitForFunction(() => !document.querySelector('.minimap-asset') && !document.querySelector('.minimap-note'));
  await page.evaluate(() => { window.minimapQA.setSearch(''); window.minimapQA.setGroups([]); window.minimapQA.setAssets([]); window.minimapQA.setText([]); });
  await map().getByText('暂无内容').waitFor();
  await page.evaluate(() => window.minimapQA.setMode('standard')); await page.waitForSelector('.standard-text-surface'); assert.equal(await map().count(), 0);
  await page.evaluate(() => window.minimapQA.setMode('inner')); await map().waitFor();
  await page.evaluate(() => document.querySelector('.app-shell').classList.add('immersive')); assert.equal(await map().isVisible(), false);
  await page.evaluate(() => document.querySelector('.app-shell').classList.remove('immersive'));
  await page.setViewportSize({ width: 500, height: 400 }); await page.waitForTimeout(80); near((await map().boundingBox()).width, 160);
  await page.setViewportSize({ width: 220, height: 170 }); await page.waitForTimeout(80); assert.equal(await map().count(), 0);
  await page.setViewportSize({ width: 1280, height: 820 }); await map().waitFor();
  for (const theme of ['dark', 'light']) { await page.evaluate(theme => window.minimapQA.setTheme(theme), theme); await page.screenshot({ path: path.join(output, `inner-${theme}.png`) }); }
  await page.evaluate(() => window.minimapQA.setMode('outer')); await page.screenshot({ path: path.join(output, 'outer-empty.png') });
  checks.push('搜索、空画布、标准详情不重复、沉浸模式、160px窄屏、空间不足恢复、明暗主题');
  assert.deepEqual(errors, []);
  await writeFile(path.join(output, 'result.json'), JSON.stringify({ checks, errors }, null, 2)); console.log(JSON.stringify({ checks, errors }, null, 2));
} finally { await page.screenshot({ path: path.join(output, 'last-state.png') }).catch(() => {}); await browser.close(); }
